targets:
  $default:
    builders:
      theme_extension_gen|theme_extension_gen: # Измените на theme_extension_gen
        generate_for:
          - lib/**/*.dart

builders:
  theme_extension_gen: # Должно совпадать с использованием выше
    target: ":theme_extension_gen"
    import: "package:theme_extension_gen/builder.dart"
    builder_factories: ["themeExtensionGenerator"] # И вашей функции
    build_extensions: { ".dart": [".theme.g.dart"] }
    auto_apply: dependents
    build_to: source
    #applies_builders: ["source_gen|combining_builder"]
