name: theme_extension_gen
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  meta: ^1.16.0
  source_gen: ^4.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.8.0
