name: theme_extension_gen
description: Package for generating theme-extensions
version: 1.0.1

repository: https://github.com/DiFo89/theme_extension_gen
homepage: https://github.com/DiFo89/theme_extension_gen
license: MIT

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  analyzer: ^8.1.1
  build: ^4.0.0
  meta: ^1.16.0
  source_gen: ^4.0.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
  build_runner: ^2.8.0
